name: build dockerimage 
on: push 
jobs:
 create-image:
   runs-on: ubuntu-latest
   steps:
    - name : checkout
      uses: actions/checkouts@v3
    - name : create docker image
      run: docker build -t  testimage .
   
 
